from pathlib import Path
exec(Path(__file__).with_name('check.py').read_text(encoding='utf-8').split("admin=requests.Session()")[0])
admin=requests.Session();guest=requests.Session();preview=requests.Session()
admin.post(base+'/admin/login.php',data={'email':'admin@example.test','password':'Test-only-0.9-password'})
token=csrf(admin,'/admin/settings.php')
admin.post(base+'/admin/settings.php',data={'csrf':token,'maintenance_mode':'1','maintenance_password':'Preview-one-123'})
ok('Closed search returns 503',guest.get(base+'/search.php',params={'q':'книги'}).status_code==503)
ok('Wrong preview password denied',preview.post(base+'/',data={'maintenance_password':'wrong'}).status_code==503)
ok('Correct preview password permits reading',preview.post(base+'/',data={'maintenance_password':'Preview-one-123'}).status_code==200)
ok('Preview still sends noindex','noindex' in preview.get(base+'/').headers.get('X-Robots-Tag',''))
r=preview.get(base+'/auth.php?mode=register');ok('Preview cannot register','name="accept_rules"' not in r.text)
admin.post(base+'/admin/settings.php',data={'csrf':token,'maintenance_mode':'1','maintenance_password':'Preview-two-123'})
ok('Password rotation revokes preview',preview.get(base+'/').status_code==503)
admin.post(base+'/admin/settings.php',data={'csrf':token,'confirm_open':'1','clear_password':'1'})
reader=requests.Session();token=csrf(reader,'/auth.php');reader.post(base+'/auth.php',data={'csrf':token,'email':'reader@example.test','password':'Test-only-reader-password'})
db=sqlite3.connect(root/'build-0.9/storage/forum.sqlite');uid=db.execute("SELECT id FROM users WHERE email='reader@example.test'").fetchone()[0]
token=csrf(admin,'/admin/users.php');admin.post(base+'/admin/users.php',data={'csrf':token,'id':uid})
ok('Ban revokes existing session','Читач' not in reader.get(base+'/profile.php').text)
admin.post(base+'/admin/users.php',data={'csrf':token,'id':uid})
token=csrf(admin,'/admin/categories.php');before=db.execute('SELECT id,sort_order FROM categories ORDER BY id').fetchall()
admin.post(base+'/admin/categories.php',data={'csrf':token,'action':'reorder','order':'1,1'})
ok('Malformed reorder rejected',before==db.execute('SELECT id,sort_order FROM categories ORDER BY id').fetchall())
ok('CSRF mutation rejected',admin.post(base+'/admin/categories.php',data={'action':'toggle','id':'1'}).status_code==419)
(root/'access-checks.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps(checks))

