import sqlite3,re,json,time
from pathlib import Path
exec(Path("forum-work/check.py").read_text(encoding="utf-8").split("root=Path(__file__)")[0])
from pathlib import Path
root=Path('forum-work');db=sqlite3.connect(root/'build-0.9/storage/forum.sqlite');base='http://127.0.0.1:8099';s=requests.Session();r=s.get(base+'/auth.php');token=re.search(r'name="csrf" value="([^"]+)"',r.text)[1];s.post(base+'/auth.php',data={'csrf':token,'email':'admin@example.test','password':'Test-only-0.9-password'});s.get(base+'/admin/users.php');checks=[]
def ok(v,n):
 assert v,n
 checks.append(n)
def post(action,**kw):
 r=s.get(base+'/admin/users.php');t=re.search(r'name="csrf" value="([^"]+)"',r.text)[1];return s.post(base+'/admin/users.php',data={'csrf':t,'action':action,**kw})
row=db.execute("SELECT password_hash FROM users WHERE email='reader@example.test'").fetchone();db.execute("INSERT INTO users(display_name,email,password_hash,role) VALUES('Delete test','delete-case@example.test',?,'member')",row);uid=db.execute('SELECT last_insert_rowid()').fetchone()[0];db.commit()
r=post('ban',id=uid,days=1,reason='test');ok('Бан застосовано' in r.text,'temporary ban');ok(db.execute('SELECT until_at FROM account_bans WHERE user_id=?',(uid,)).fetchone()[0]>time.time(),'expiration saved')
db.execute('UPDATE account_bans SET until_at=? WHERE user_id=?',(int(time.time())-1,uid));db.commit();s.get(base+'/admin/users.php');ok(db.execute('SELECT blocked_at FROM users WHERE id=?',(uid,)).fetchone()[0] is None,'automatic expiration')
post('ban',id=uid,days=0);ok(db.execute('SELECT until_at FROM account_bans WHERE user_id=?',(uid,)).fetchone()==(None,),'permanent ban');post('unban',id=uid);ok(db.execute('SELECT blocked_at FROM users WHERE id=?',(uid,)).fetchone()[0] is None,'unban')
adminid=db.execute("SELECT id FROM users WHERE email='admin@example.test'").fetchone()[0];post('delete',id=adminid,confirm_delete=1);ok(db.execute('SELECT id FROM users WHERE id=?',(adminid,)).fetchone() is not None,'protect admin')
post('delete',id=uid);ok(db.execute('SELECT id FROM users WHERE id=?',(uid,)).fetchone() is not None,'confirmation required')
cat=db.execute('SELECT id FROM categories LIMIT 1').fetchone()[0];db.execute("INSERT INTO topics(category_id,user_id,title,slug,body) VALUES(?,?,'Deletion QA','deletion-qa','Preserved content')",(cat,uid));tid=db.execute('SELECT last_insert_rowid()').fetchone()[0];db.execute('INSERT INTO subscriptions(user_id,topic_id) VALUES(?,?)',(uid,tid));db.execute("INSERT INTO identities(user_id,provider,provider_uid) VALUES(?,'telegram','qa-uid')",(uid,));db.commit();r=post('delete',id=uid,confirm_delete=1,deny_return=1);ok('Акаунт видалено' in r.text,'delete account');ok(db.execute('SELECT user_id,body FROM topics WHERE id=?',(tid,)).fetchone()==(None,'Preserved content'),'preserve discussion');ok(db.execute('SELECT COUNT(*) FROM registration_bans').fetchone()[0]>=2,'email and social identity bans');ok(db.execute('SELECT COUNT(*) FROM identities WHERE user_id=?',(uid,)).fetchone()[0]==0,'delete identities')
post('registration');guest=requests.Session();r=guest.get(base+'/auth.php?mode=register');ok('name="display_name"' not in r.text,'registration switch off');post('registration',registration_open=1)
r=guest.get(base+'/auth.php?mode=register');t=re.search(r'name="csrf" value="([^"]+)"',r.text)[1];r=guest.post(base+'/auth.php?mode=register',data={'csrf':t,'action':'register','email':'DELETE-CASE@example.test','password':'Test-only-test-password','display_name':'Test','accept_rules':1});ok('Реєстрація для цього акаунта недоступна' in r.text,'case-insensitive return ban');post('unban_registration',label='Видалений акаунт #'+str(uid));ok(db.execute('SELECT COUNT(*) FROM registration_bans WHERE label=?',('Видалений акаунт #'+str(uid),)).fetchone()[0]==0,'remove return ban');db.execute('DELETE FROM topics WHERE id=?',(tid,));db.commit();db.close();(root/'user-checks.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2),encoding='utf-8');print(len(checks),'user checks passed')
